services:
  - type: web
    runtime: python
    name: threat-mobileye-dashboard
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: VT_API_KEY
        sync: false
      - key: ABUSEIPDB_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
